import '@/styles/globals.css';
import { GlobalStyle } from '@/utils/GlobalStyle';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import 'swiper/css';
import 'swiper/css/free-mode';
import 'swiper/css/pagination';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>TechTime</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <Component {...pageProps} />
    </>
  );
}
